### PR TITLE
Use partial namespace CSS

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
After https://github.com/w3c/css-houdini-drafts/pull/784 I think this will be the last `partial interface CSS` anywhere. @tabatkins, I didn't update index.html, can you see to that as well?

**Comment by tabatkins** [comment]
Will do, thanks!

**Comment by foolip** [comment]
@tabatkins, index.html not updated, just checking to see if that was an oversight or if you're doing it separately.

**Comment by tabatkins** [comment]
Separately.

**Pull request merged**
